version: '3.8'

services:
  universal-connector:
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    container_name: universal-connector-server
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - RUST_LOG=info
      - HTTP_ADDR=0.0.0.0:8080
      - WS_ADDR=0.0.0.0:8081
      - ENABLE_LSP=false
      - ENABLE_HTTP=true
      - ENABLE_WS=true
    volumes:
      - connector-data:/app/data:Z
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  connector-data:
